import PDFDocument from "pdfkit";
import QRCode from "qrcode";

export interface CertificateDocumentData {
  certificateNumber: string;
  typeLabel: string;
  studentName: string;
  studentNo: string;
  department: string;
  semester: number;
  section: string;
  issuedDate: string;
  verificationUrl: string;
  bodyLines: string[];
}

/**
 * Renders the official-looking demo certificate as a PDF buffer.
 * Deterministic from the supplied data: downloads regenerate on demand,
 * so no document files are stored anywhere.
 */
export async function renderCertificatePdf(data: CertificateDocumentData): Promise<Buffer> {
  const qrPng = await QRCode.toBuffer(data.verificationUrl, {
    width: 180,
    margin: 1,
    errorCorrectionLevel: "M",
  });

  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 64 });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", (error: Error) => reject(error));

    try {
      doc.font("Helvetica-Bold").fontSize(22).text("SmartCampus", { align: "center" });
      doc.font("Helvetica").fontSize(10).fillColor("#555555")
        .text("Demo Institution  ·  Demonstration documents only", { align: "center" });
      doc.moveDown(0.4);
      doc.fillColor("#000000").font("Helvetica-Bold").fontSize(17).text(data.typeLabel, { align: "center" });
      doc.moveDown(0.2);
      doc.font("Helvetica").fontSize(10).fillColor("#555555")
        .text(`Certificate No: ${data.certificateNumber}`, { align: "center" });
      doc.moveDown(1);

      doc.fillColor("#000000").fontSize(12);
      doc.text(`This is to certify that ${data.studentName} (${data.studentNo}),`);
      doc.text(`a student of ${data.department}, Semester ${data.semester}, Section ${data.section},`);
      doc.moveDown(0.6);
      for (const line of data.bodyLines) {
        doc.fontSize(11).text(line);
        doc.moveDown(0.3);
      }
      doc.moveDown(0.8);
      doc.fontSize(11).text(`Issued on: ${data.issuedDate}`);
      doc.moveDown(1.2);

      const qrSize = 130;
      const qrX = doc.page.width - doc.page.margins.right - qrSize;
      const qrY = doc.y;
      doc.image(qrPng, qrX, qrY, { width: qrSize, height: qrSize });
      doc.fontSize(10).fillColor("#000000").text("Registrar (Demo)", 64, qrY + 20);
      doc.fontSize(8).fillColor("#555555").text("Authorized signatory placeholder", 64, qrY + 36);
      doc.fontSize(9).fillColor("#000000")
        .text("Verify this certificate:", qrX, qrY + qrSize + 8, { width: qrSize });
      doc.fontSize(7).fillColor("#0b5fff").text(data.verificationUrl, qrX, doc.y + 2, { width: 220 });

      doc.moveDown(3);
      doc.fontSize(8).fillColor("#777777").text(
        "This is an official-looking demonstration document generated by SmartCampus. " +
        "It is not a government-issued certificate. Authenticity can be checked at the verification URL above.",
        { align: "center" },
      );

      doc.end();
    } catch (error) {
      reject(error instanceof Error ? error : new Error(String(error)));
    }
  });
}
